In [1]:
#Pandas is a fast and powerful data manipulation library for Python. 
# It provides data structures and functions needed to manipulate structured data seamlessly. 
# With Pandas, you can easily handle and analyze large datasets, perform data cleaning, and conduct various data transformations. 
# It is widely used in data science, machine learning, and statistical analysis for its efficiency and ease of use.

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# ensure pandas is installed in the current Jupyter kernel
%pip install pandas

import pandas as pd

Requirement already satisfied: pandas in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('services.csv') # read_csv is a function in the pandas library that allows you to read a CSV (Comma-Separated Values) file and create a DataFrame from it.

In [6]:
df0=pd.read_csv('services.csv',header=None) # read_csv is a function in the pandas library that allows you to read a CSV (Comma-Separated Values) file and create a DataFrame from it. The header=None argument indicates that the CSV file does not have a header row, so pandas will assign default column names (0, 1, 2, etc.) to the DataFrame.

In [7]:
df0

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [8]:
df2=pd.read_csv('services.csv',skiprows = 2) # read_csv is a function in the pandas library that allows you to read a CSV (Comma-Separated Values) file and create a DataFrame from it. The skiprows=2 argument tells pandas to skip the first two rows of the CSV file when reading it, which can be useful if those rows contain metadata or other non-data information.
df2

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [9]:
df1=pd.read_csv('services.csv', usecols=['program_id','application_process']) # read_csv is a function in the pandas library that allows you to read a CSV (Comma-Separated Values) file and create a DataFrame from it. The usecols=['program_id','application_process'] argument specifies that only the columns named 'program_id' and 'application_process' should be read from the CSV file, which can help reduce memory usage and improve performance when working with large datasets.
df1

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [10]:
#What is dataframe in pandas?
#A DataFrame in pandas is a two-dimensional, size-mutable, 
# and heterogeneous data structure that can hold 
# data of different types (such as integers, floats, strings, etc.). 
# It is similar to a table in a relational database or an Excel spreadsheet. 
# A DataFrame consists of rows and columns, where each column can be 
# thought of as a Series (a one-dimensional array) and each row 
# represents a record. DataFrames provide powerful tools for 
# data manipulation, analysis, and visualization, making them a 
# fundamental component of the pandas library.


#data structure >> series and dataframe
#series >> 1 dimensional in nature
#dataframe >> 2 dimensional in nature, multple series constitute a dataframe

In [11]:
type(df) # type() is a built-in function in Python that returns the type of an object. In this case, it will return <class 'pandas.core.frame.DataFrame'>, indicating that the variable df is a DataFrame object from the pandas library.

pandas.DataFrame

In [12]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [13]:
df.application_process # This code is accessing the 'application_process' column of the DataFrame df. It will return a Series object containing the values of that column. If the column name contains spaces or special characters, you may need to use df['application_process'] instead to access it.

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [14]:
df['application_process'] 
#Prefer this method to access the column when the column name contains spaces or special characters, as it allows you to access the column without using dot notation.
# This code is accessing the 'application_process' column of the DataFrame df using the bracket notation. It will return a Series object containing the values of that column. This method is often used when the column name contains spaces or special characters, as it allows you to access the column without using dot notation.

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [15]:
type(df['application_process']) # This code is checking the type of the object returned by df['application_process']. It will return <class 'pandas.core.series.Series'>, indicating that the 'application_process' column is a Series object in pandas.

pandas.Series

In [16]:
type(df)

pandas.DataFrame

In [17]:
l=[1,2,3,4]
s=pd.Series(l) # A Series in pandas is a one-dimensional array-like object that can hold data of any type (integers, floats, strings, etc.). It is similar to a column in a DataFrame. The code s=pd.Series(l) creates a Series object from the list l, where each element of the list becomes an element in the Series. The resulting Series will have an index (0, 1, 2, 3) corresponding to the position of each element in the original list.
s

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
#In Numpy there we use arrray, in pandas we use series and dataframe.

In [19]:
type(s)

pandas.Series

In [20]:
s[3] # This code is accessing the element at index 3 of the Series s. Since the Series was created from the list [1, 2, 3, 4], the element at index 3 is 4. Therefore, this code will return the value 4.

np.int64(4)

In [21]:
s[2:3] # This code is slicing the Series s to retrieve a subset of its elements. The slice [2:3] means that it will return the element at index 2 (the third element) and exclude the element at index 3. In this case, it will return a Series containing the value 3, which is the element at index 2 in the original Series s.

2    3
dtype: int64

In [22]:
s[2:]  # This code is slicing the Series s to retrieve a subset of its elements starting from index 2 to the end of the Series. The slice [2:] means that it will include all elements from index 2 (the third element) to the last element of the Series. In this case, it will return a Series containing the values 3 and 4, which are the elements at index 2 and 3 in the original Series s.

2    3
3    4
dtype: int64

In [23]:
d=pd.Series([100,200,300], index=['a','b','c']) # This code creates a pandas Series with the values 100, 200, and 300, and assigns custom index labels 'a', 'b', and 'c' to each element. The resulting Series will look like this:

In [24]:
d

a    100
b    200
c    300
dtype: int64

In [25]:
type(d)

pandas.Series

In [26]:
d['b'] # This code is accessing the element in the Series d that has the index label 'b'. Since the Series was created with the values [100, 200, 300] and corresponding index labels ['a', 'b', 'c'], the element at index 'b' is 200. Therefore, this code will return the value 200.

np.int64(200)

In [27]:
d.index # This code is accessing the index of the Series d. The index is a sequence of labels that correspond to the elements in the Series. In this case, since the Series was created with custom index labels ['a', 'b', 'c'], this code will return an Index object containing those labels: Index(['a', 'b', 'c'], dtype='object').

Index(['a', 'b', 'c'], dtype='str')

In [28]:
d["a":"c"] # This code is slicing the Series d to retrieve a subset of its elements based on the index labels. The slice ["a":"c"] means that it will include all elements from index 'a' to index 'c', inclusive. In this case, it will return a Series containing the values 100, 200, and 300, which correspond to the index labels 'a', 'b', and 'c' in the original Series d.

a    100
b    200
c    300
dtype: int64

In [29]:
d.reset_index() # This code is resetting the index of the Series d to the default integer index. The reset_index() method will create a new DataFrame with the original index as a column and a new default integer index (0, 1, 2, etc.). If you want to drop the original index and only keep the values, you can use d.reset_index(drop=True) instead.

  index    0
0     a  100
1     b  200
2     c  300

In [30]:
d.reset_index(drop=True) # This code is resetting the index of the Series d to the default integer index while dropping the original index. The reset_index(drop=True) method will create a new Series with a new default integer index (0, 1, 2, etc.) and will not include the original index as a column in the resulting Series.

0    100
1    200
2    300
dtype: int64

In [31]:
pd.DataFrame(d) # This code is converting the Series s into a DataFrame. The resulting DataFrame will have a single column containing the values from the Series, and the index of the Series will become the index of the DataFrame. The column name will be 0 by default, but you can specify a different column name if desired.

     0
a  100
b  200
c  300

In [32]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [33]:
df.shape # This code is accessing the shape of the DataFrame df. The shape attribute returns a tuple representing the dimensions of the DataFrame, where the first element is the number of rows and the second element is the number of columns. For example, if df has 100 rows and 5 columns, df.shape will return (100, 5).

(23, 22)

In [34]:
df.columns # This code is accessing the columns of the DataFrame df. The columns attribute returns an Index object containing the column labels of the DataFrame. For example, if df has columns 'A', 'B', and 'C', df.columns will return Index(['A', 'B', 'C'], dtype='object').

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [35]:
list(df.columns) # This code is converting the Index object returned by df.columns into a regular Python list. The list() function takes an iterable (in this case, the Index object) and returns a list containing the same elements. For example, if df.columns returns Index(['A', 'B', 'C'], dtype='object'), then list(df.columns) will return ['A', 'B', 'C'].

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [36]:
df.head(5) # This code is accessing the first 5 rows of the DataFrame df. The head() method returns a new DataFrame containing the specified number of rows from the top of the original DataFrame. If you want to see a different number of rows, you can pass that number as an argument to the head() method (e.g., df.head(10) for the first 10 rows).

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [37]:
df.head(2) # This code is accessing the first 2 rows of the DataFrame df. The head() method returns a new DataFrame containing the specified number of rows from the top of the original DataFrame. In this case, it will return a DataFrame with the first 2 rows of df.

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [38]:
df.tail(5) # This code is accessing the last 5 rows of the DataFrame df. The tail() method returns a new DataFrame containing the specified number of rows from the bottom of the original DataFrame. If you want to see a different number of rows, you can pass that number as an argument to the tail() method (e.g., df.tail(10) for the last 10 rows).

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [39]:
df.sample(2) # This code is randomly sampling 2 rows from the DataFrame df. The sample() method returns a new DataFrame containing the specified number of randomly selected rows from the original DataFrame. If you want to sample a different number of rows, you can pass that number

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN

In [40]:
df.info() # This code is calling the info() method on the DataFrame df. The info() method provides a concise summary of the DataFrame, including the number of non-null entries in each column, the data type of each column, and the memory usage of the DataFrame. It is a useful method for quickly understanding the structure and contents of a DataFrame.

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      str
 4   alternate_name           1 non-null      str
 5   application_process      23 non-null     str
 6   audience                 14 non-null     str
 7   description              23 non-null     str
 8   eligibility              17 non-null     str
 9   email                    1 non-null      str
 10  fees                     21 non-null     str
 11  funding_sources          21 non-null     str
 12  interpretation_services  1 non-null      str
 13  keywords                 21 non-null     str
 14  languages                1 non-null      str
 15  name                     23 non-null     str
 16  required_documents       1 non-null      str
 17  service_areas            21 non-null     str
 18  status                   23 non-null     str
 19  wait_time                19 non-null     str
 20  website                  2 non-null      str
 21  taxonomy_ids             1 non-null      str
dtypes: float64(1), int64(2), str(19)
memory usage: 4.1 KB

In [41]:
df.dtypes # This code is accessing the data types of each column in the DataFrame df. The dtypes attribute returns a Series containing the data type of each column in the DataFrame. For example, if df has columns 'A', 'B', and 'C' with data types int64, float64, and object respectively, df.dtypes will return:

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [42]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [43]:
df['id'] # This code is accessing the 'id' column of the DataFrame df. It will return a Series object containing the values of that column. If the column name contains spaces or special characters, you may need to use df['id'] instead to access it.

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [44]:
df['application_process'] # This code is accessing the 'application_process' column of the DataFrame df using the bracket notation. It will return a Series object containing the values of that column. This method is often used when the column name contains spaces or special characters, as it allows you to access the column without using dot notation.

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [45]:
type(df['application_process']) # This code is checking the type of the object returned by df['application_process']. It will return <class 'pandas.core.series.Series'>, indicating that the 'application_process' column is a Series object in pandas.

pandas.Series

In [46]:
list[(df['application_process'])] # This code is converting the type of the object returned by df['application_process'] into a list. However, since type(df['application_process']) returns a single type object (e.g., <class 'pandas.core.series.Series'>), wrapping it in list() will create a list containing that single type object. The result will be: [<class 'pandas.core.series.Series'>].

list[0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str]

In [47]:
#Series to DataFrame

pd.Series([2,3,4], index=[100,'Pashupati',2]) # This code is creating a pandas Series with the values 2, 3, and 4, and assigning custom index labels 100, 'Pashupati', and 2 to each element. The resulting Series will look like this:

100          2
Pashupati    3
2            4
dtype: int64

In [48]:
d=pd.DataFrame(pd.Series([2,3,4], index=[100,'Pashupati',2])) # This code is creating a pandas Series with the values 2, 3, and 4, and assigning custom index labels 100, 'Pashupati', and 2 to each element. Then, it is converting that Series into a DataFrame. The resulting DataFrame will have a single column containing the values from the Series, and the index of the Series will become the index of the DataFrame. The column name will be 0 by default, but you can specify a different column name if desired.

In [49]:
d

           0
100        2
Pashupati  3
2          4

In [50]:
d['new colum']='Pashupati' # This code is adding a new column named 'new colum' to the DataFrame d and assigning the value 'Pashupati' to all rows in that column. After executing this code, the DataFrame d will have an additional column with the specified name and value.

In [51]:
d

           0  new colum
100        2  Pashupati
Pashupati  3  Pashupati
2          4  Pashupati

In [52]:
d['new colum'] # This code is accessing the 'new colum' column of the DataFrame d. It will return a Series object containing the values of that column, which in this case will be 'Pashupati' for all rows.

100          Pashupati
Pashupati    Pashupati
2            Pashupati
Name: new colum, dtype: str

In [53]:
d

           0  new colum
100        2  Pashupati
Pashupati  3  Pashupati
2          4  Pashupati

In [54]:
d.columns=['id','new_name'] # This code is attempting to rename the columns of the DataFrame d by assigning a new list of column names to the colums attribute. However, there is a typo in the attribute name; it should be columns instead of colums. The correct code should be:

In [55]:
d

           id   new_name
100         2  Pashupati
Pashupati   3  Pashupati
2           4  Pashupati

In [56]:
d.reset_index() # This code is resetting the index of the Series d to the default integer index. The reset_index() method will create a new DataFrame with the original index as a column and a new default integer index (0, 1, 2, etc.). If you want to drop the original index and just have the default integer index, you can use d.reset_index(drop=True).

       index  id   new_name
0        100   2  Pashupati
1  Pashupati   3  Pashupati
2          2   4  Pashupati

In [57]:
d.reset_index(drop=True) # This code is resetting the index of the Series d to the default integer index while dropping the original index. The reset_index(drop=True) method will create a new Series with a new default integer index (0, 1, 2, etc.) and will not include the original index as a column in the resulting Series.

   id   new_name
0   2  Pashupati
1   3  Pashupati
2   4  Pashupati

In [58]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [59]:
df.required_documents

0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
5                                          NaN
6                                          NaN
7                                          NaN
8                                          NaN
9                                          NaN
10                                         NaN
11                                         NaN
12                                         NaN
13                                         NaN
14                                         NaN
15                                         NaN
16                                         NaN
17                                         NaN
18                                         NaN
19                                         NaN
20                                         NaN
21    Government-issued picture identification
22                                         NaN
Name: required_documents, dtype: str

In [60]:
df.status

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: str

In [61]:
df[['name','languages','status']] 
# This code is accessing multiple columns ('name', 'language', and 'status') from the DataFrame df using double bracket notation. It will return a new DataFrame containing only those specified columns. Each of the columns will be included in the resulting DataFrame, and the index will remain the same as in the original DataFrame df.
#Why we use 2 brackets to access multiple columns in pandas?
#In pandas, we use double brackets (e.g., df[['column1', 'column2']]) to access multiple columns from a DataFrame because it allows us to specify a list of column names that we want to retrieve. The double brackets indicate that we are passing a list of column names to the DataFrame, which tells pandas to return a new DataFrame containing only those specified columns. If we were to use single brackets (e.g., df['column1']), it would return a Series object for that single column instead of a DataFrame. Therefore, using double brackets is necessary when we want to access multiple columns and maintain the DataFrame structure.

                                    name languages    status
0        Fair Oaks Adult Activity Center       NaN    active
1       Second Career Employment Program       NaN    active
2                 Senior Peer Counseling       NaN    active
3               Family Visitation Center       NaN    active
4      Economic Self-Sufficiency Program       NaN    active
5   Little House Recreational Activities       NaN    active
6       Rosener House Adult Day Services       NaN    active
7         Meals on Wheels - South County       NaN    active
8                       Fair Oaks Branch       NaN    active
9                           Main Library       NaN    active
10                       Schaberg Branch       NaN    active
11                          Project Read       NaN    active
12                 Redwood Shores Branch       NaN    active
13                    Redwood City Corps       NaN    active
14           Adult Rehabilitation Center       NaN    active
15                       Sunnyvale Corps       NaN    active
16     South San Francisco Citadel Corps       NaN    active
17                         Project Smile       NaN    active
18         San Mateo Free Medical Clinic       NaN    active
19             Service with blank fields       NaN   defunct
20       Service for Admin Test Location       NaN  inactive
21                       Passport Photos   Spanish    active
22                  Example Service Name       NaN    active

In [62]:
pip install openpyxl # This code is using pip, the package installer for Python, to install the openpyxl library

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

In [63]:
dfxl=pd.read_excel('LUSID Excel - Setting up your market data.xlsx') # This code is using the read_excel() function from the pandas library to read an Excel file named 'LUSID Excel - Setting up your market data'. The read_excel() function allows you to read data from an Excel file and create a DataFrame from it. You can specify additional parameters such as sheet name, header row, and more if needed.

In [64]:
dfxl

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [65]:
dfxl.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [66]:
dfxl.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3        str
Unnamed: 4        str
Unnamed: 5     object
Unnamed: 6    float64
Unnamed: 7        str
Unnamed: 8        str
Unnamed: 9        str
dtype: object

In [67]:
dfxl.shape

(28, 10)

In [68]:
dfxl.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  0 non-null      float64
 2   Unnamed: 2  0 non-null      float64
 3   Unnamed: 3  3 non-null      str
 4   Unnamed: 4  12 non-null     str
 5   Unnamed: 5  7 non-null      object
 6   Unnamed: 6  0 non-null      float64
 7   Unnamed: 7  6 non-null      str
 8   Unnamed: 8  4 non-null      str
 9   Unnamed: 9  1 non-null      str
dtypes: float64(4), object(1), str(5)
memory usage: 2.3+ KB

In [69]:
dfon=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv') # This code is using the read_csv() function from the pandas library to read a CSV file from a specified URL. The URL points to a raw CSV file containing the Titanic dataset. The read_csv() function will download the CSV file from the URL and create a DataFrame from it, allowing you to work with the data in Python.

In [70]:
dfon

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [71]:
dfon.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [72]:
dfon.shape

(891, 12)

In [73]:
dfon.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [74]:
dfon['Sex']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [75]:
dfon[['PassengerId','Fare','Pclass']] # This code is accessing multiple columns ('PassengerId', 'Fare', and 'Pclass') from the DataFrame dfon using double bracket notation. It will return a new DataFrame containing only those specified columns. Each of the columns will be included in the resulting DataFrame, and the index will remain the same as in the original DataFrame dfon.

     PassengerId     Fare  Pclass
0              1   7.2500       3
1              2  71.2833       1
2              3   7.9250       3
3              4  53.1000       1
4              5   8.0500       3
..           ...      ...     ...
886          887  13.0000       2
887          888  30.0000       1
888          889  23.4500       3
889          890  30.0000       1
890          891   7.7500       3

[891 rows x 3 columns]

In [86]:
pip install lxml

Requirement already satisfied: lxml in c:\users\pashu\desktop\data analyst\venv\lib\site-packages (6.0.2)
Note: you may need to restart the kernel to use updated packages.

In [77]:
import lxml

In [ ]:
import pandas as pd
pd.read_html("www.google.com") # This code is using the read_html() function from the pandas library to read HTML tables from the specified URL (www.google.com). The read_html() function will attempt to parse the HTML content of the webpage and extract any tables it finds, returning a list of DataFrames corresponding to each table. Note that the success of this operation depends on the structure of the webpage and whether it contains any HTML tables.

In [88]:
df.to_csv("employee.csv", index=False) # This code is using the to_csv() method of a DataFrame (df) to save the DataFrame to a CSV file named "employee.csv". The index=False argument specifies that the index of the DataFrame should not be included in the output CSV file. If you want to include the index, you can simply omit the index argument or set it to True.

In [89]:
#To read Json file in pandas
url='https://api.github.com/repos/pandas-dev/pandas/issues'
pd.read_json(url) # This code is using the read_json() function from the pandas library to read a JSON file from the specified URL. The read_json() function will attempt to parse the JSON content from the URL and create a DataFrame from it. The structure of the resulting DataFrame will depend on the structure of the JSON data at the given URL.

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,pull_request,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason,sub_issues_summary,issue_dependencies_summary,pinned_comment
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64261,3971462021,PR_kwDOAA0YD87FUDHc,64261,DOC: Fix ES01 for pandas.api.types,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] related to #60365\r\n,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64260,3971436951,PR_kwDOAA0YD87FT90S,64260,DOC: Fix ES01 for pandas.Timestamp,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] related to #60365\r\n,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64259,3971385688,PR_kwDOAA0YD87FTzRQ,64259,DOC: Fix ES01 for pandas.Series,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] related #60365\r\n,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64258,3970994662,PR_kwDOAA0YD87FSmTX,64258,PERF: PeriodArray._from_sequence,...,{'url': 'https://api.github.com/repos/pandas-d...,Avoid repeated string parsing in to_offset\r\n...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64255,3969718878,I_kwDOAA0YD87snRpe,64255,ENH: `series.argsort(stable=True)` currently d...,...,NaN,### Feature Type\n\n- [ ] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64254,3969604459,PR_kwDOAA0YD87FOI4w,64254,DOC: Fix source link to use main branch (#64224),...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #64224\r\n- [ ] Tests added and p...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64253,3968149108,I_kwDOAA0YD87shSZ0,64253,BUG: The order of items in `pd.concat` matters...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64252,3967955897,I_kwDOAA0YD87sgjO5,64252,BUG: inconsitant parsing of dates with us to n...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64251,3967135679,PR_kwDOAA0YD87FF6Ag,64251,PERF: avoid materializing values[indexer] in B...,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #64250\n- [x] [Tests added and pa...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64250,3967079315,I_kwDOAA0YD87sdNOT,64250,PERF: object-dtype iloc setitem with datetimel...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64241,3963719125,I_kwDOAA0YD87sQY3V,64241,API: PeriodIndex(dt64_data) depends on contain...,...,NaN,"```\ndata = np.arange(5).view(""M8[D]"").astype(...",NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64240,3963700933,I_kwDOAA0YD87sQUbF,64240,BUG: Inconsistent handling of offsets in `to_t...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64239,3963550515,I_kwDOAA0YD87sPvsz,64239,BUG: convert_dtypes does not correctly set the...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64238,3963522385,I_kwDOAA0YD87sPo1R,64238,"BUG: convert_dtype with dtype_backend=""numpy_n...",...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64236,3961290997,PR_kwDOAA0YD87Eyzse,64236,DOC: Update documentation for apply function b...,...,{'url': 'https://api.github.com/repos/pandas-d...,Clarify behavior of function application with ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64235,3961139442,PR_kwDOAA0YD87EyUXE,64235,BUG: normalize_json no longer supports top-lev...,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #64188 (Replace xxxx with the Git...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64233,3960731020,PR_kwDOAA0YD87ExBku,64233,fix: bug posixpath inside Series,...,{'url': 'https://api.github.com/repos/pandas-d...,# BUG: Fix ArrowInvalid error with chained Pat...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64230,3959337713,PR_kwDOAA0YD87EshgO,64230,PERF: avoid wasteful array round-trip in loc/i...,...,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #64229\r\n,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64229,3959328614,I_kwDOAA0YD87r_o9m,64229,PERF: loc/iloc setitem with list-of-lists unne...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64227,3958761874,I_kwDOAA0YD87r9emS,64227,API: PeriodArray._from_sequence(ints),...,NaN,We have three constructors for a PeriodArray: ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64224,3958336137,I_kwDOAA0YD87r72qJ,64224,DOC: wrong source link for `pandas.DataFrame`,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64223,3958286774,I_kwDOAA0YD87r7qm2,64223,DOC: source links not working: 404 on GitHub,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64215,3956322561,PR_kwDOAA0YD87EikrB,64215,BUG: Fix unstack with sort=False for MultiInde...,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #64150 \r\n- [x] [Tests added and...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64212,3955428145,PR_kwDOAA0YD87EfwRo,64212,depr: offset name,...,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #64207(Replace xxxx with the GitH...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64207,3954767549,I_kwDOAA0YD87ruPa9,64207,DEPR: Offset.name,...,NaN,DateOffset.name is an alias of rule_code. We ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64203,3954528672,PR_kwDOAA0YD87Ecz46,64203,DOC: add py:type targets for typing aliases,...,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64202,3953929665,PR_kwDOAA0YD87Ea09z,64202,BUG: Fix precision loss in to_numeric for inte...,...,{'url': 'https://api.github.com/repos/pandas-d...,This PR fixes a precision issue in pd.to_numer...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64198,3953678338,I_kwDOAA0YD87rqFgC,64198,BUG: `read_excel` with `usecols` still mangle...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64196,3953363405,I_kwDOAA0YD87ro4nN,64196,BUG: For `infer_dtype` `skipna` is ignored for...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64193,3953042096,PR_kwDOAA0YD87EX5UP,64193,Fix 64188 : DOC/IO: Fix json_normalize with nu...,...,{'url': 'https://api.github.com/repos/pandas-d...,This PR addresses a bug where pd.json_normaliz...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN

In [93]:
pip install requests

Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl (107 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   -------- ------------------------------- 1/5 [idna]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

In [94]:
import requests # This code is importing the requests library, which is a popular Python library used for making HTTP requests. It allows you to send HTTP requests to a specified URL and handle the response, making it useful for tasks such as web scraping, API interactions, and more.
data=requests.get(url)

In [ ]:
data #200 means success

In [96]:
df6=data.json() # This code is calling the json() method on the response object returned by requests.get(url). The json() method parses the JSON content of the response and returns it as a Python dictionary (or list, depending on the structure of the JSON). This allows you to work with the JSON data in a more convenient format within your Python code.

In [97]:
df6

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64261',
  'id': 3971462021,
  'node_id': 'PR_kwDOAA0YD87FUDHc',
  'number': 64261,
  'title': 'DOC: Fix ES01 for pandas.api.types',
  'user': {'login': 'tuhinsharma121',
   'id': 6801780,
   'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tuhinsharma121',
   'html_url': 'https://github.com/tuhinsharma121',
   'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
   'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
   'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
   'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
   'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
   'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-02-21T06:33:08Z',
  'updated_at': '2026-02-21T06:33:19Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64261',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64261',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64261.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64261.patch',
   'merged_at': None},
  'body': '- [x] related to #60365\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64261/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64260',
  'id': 3971436951,
  'node_id': 'PR_kwDOAA0YD87FT90S',
  'number': 64260,
  'title': 'DOC: Fix ES01 for pandas.Timestamp',
  'user': {'login': 'tuhinsharma121',
   'id': 6801780,
   'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tuhinsharma121',
   'html_url': 'https://github.com/tuhinsharma121',
   'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
   'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
   'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
   'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
   'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
   'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-02-21T06:19:14Z',
  'updated_at': '2026-02-21T06:23:00Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64260',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64260',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64260.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64260.patch',
   'merged_at': None},
  'body': '- [x] related to #60365\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64260/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64259',
  'id': 3971385688,
  'node_id': 'PR_kwDOAA0YD87FTzRQ',
  'number': 64259,
  'title': 'DOC: Fix ES01 for pandas.Series',
  'user': {'login': 'tuhinsharma121',
   'id': 6801780,
   'node_id': 'MDQ6VXNlcjY4MDE3ODA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tuhinsharma121',
   'html_url': 'https://github.com/tuhinsharma121',
   'followers_url': 'https://api.github.com/users/tuhinsharma121/followers',
   'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}',
   'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions',
   'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs',
   'repos_url': 'https://api.github.com/users/tuhinsharma121/repos',
   'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-02-21T05:49:37Z',
  'updated_at': '2026-02-21T06:22:27Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64259',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64259',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64259.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64259.patch',
   'merged_at': None},
  'body': '- [x] related #60365\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64259/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64258',
  'id': 3970994662,
  'node_id': 'PR_kwDOAA0YD87FSmTX',
  'number': 64258,
  'title': 'PERF: PeriodArray._from_sequence',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-02-21T01:33:33Z',
  'updated_at': '2026-02-21T03:35:00Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64258',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64258',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64258.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64258.patch',
   'merged_at': None},
  'body': 'Avoid repeated string parsing in to_offset\r\n\r\nxref https://github.com/pandas-dev/asv-runner/issues/101#issuecomment-3930532198\r\n\r\n```\r\nfrom asv_bench.benchmarks.indexing import NonNumericSeriesIndexing as cls\r\nself = cls()\r\n\r\nself.setup("period", "unique_monotonic_inc")\r\n\r\n%timeit self.time_getitem_list_like("period", "unique_monotonic_inc")\r\n116 μs ± 654 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)  # <- main\r\n83.9 μs ± 813 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)  # <- HEAD~100\r\n70.6 μs ± 258 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)  # <- PR\r\n```\r\n\r\nxref https://github.com/pandas-dev/asv-runner/issues/100#issuecomment-3922054260\r\n\r\n```\r\nfrom asv_bench.benchmarks.period import PeriodIndexConstructor\r\nself2 = PeriodIndexConstructor()\r\nself2.setup("D", True)\r\n\r\n%timeit self2.time_from_pydatetime("D", True)\r\n1.03 ms ± 17.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)  # <- PR\r\n11.3 ms ± 203 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <- main\r\n1.08 ms ± 20.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)  # <- HEAD~100\r\n```',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64258/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/64255',
  'id': 3969718878,
  'node_id': 'I_kwDOAA0YD87snRpe',
  'number': 64255,
  'title': 'ENH: `series.argsort(stable=True)` currently does nothing',
  'user': {'login': 'yushiyangk',
   'id': 9082950,
   'node_id': 'MDQ6VXNlcjkwODI5NTA=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/9082950?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/yushiyangk',
   'html_url': 'https://github.com/yushiyangk',
   'followers_url': 'https://api.github.com/users/yushiyangk/followers',
   'following_url': 'https://api.github.com/users/yushiyangk/following{/other_user}',
   'gists_url': 'https://api.github.com/users/yushiyangk/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/yushiyangk/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/yushiyangk/subscriptions',
   'organizations_url': 'https://api.github.com/users/yushiyangk/orgs',
   'repos_url': 'https://api.github.com/users/yushiyangk/repos',
   'events_url': 'https://api.github.com/users/yushiyangk/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/yushiyangk/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1357732944,
    'node_id': 'MDU6TGFiZWwxMzU3NzMyOTQ0',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Series',
    'name': 'Series',
    'color': '8dd5fc',
    'default': False,
    'description': 'Series data structure'},
   {'id': 6323552771,
    'node_id': 'LA_kwDOAA0YD88AAAABeOnCAw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Sorting',
    'name': 'Sorting',
    'color': 'f9d0c4',
    'default': False,
    'description': 'e.g. sort_index, sort_values'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 3,
  'created_at': '2026-02-20T18:01:56Z',
  'updated_at': '2026-02-20T21:33:56Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'issue_dependencies_summary': {'blocked_by': 0,
   'total_blocked_by': 0,
   'blocking': 0,
   'total_blocking': 0},
  'body': "### Feature Type\n\n- [ ] Adding new functionality to pandas\n\n\n- [x] Changing existing functionality in pandas\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nHi, the method `pandas.Series.argsort` has an argument `stable` that currently does nothing.\n\nI am aware that it is documented that this argument does nothing. But I must ask why?\n\nThe current method is already able to perform stable sorts using `kind='stable'`. So if the `stable` argument must be present, why not have it actually do something?\n\nOf course it might conflict with the `kind` argument, e.g. if `kind='quicksort'` is specified, but there are already plenty of methods in Pandas where such arguments can potentially conflict with each other. What's important is that these complications are well-documented, which already seems to be case in the rest of the library.\n\nThe fact that this argument exists adds a lot of confusion, particularly for anyone trying to use it by glancing through method signatures or using their IDE autocomplete.\n\n### Feature Description\n\n```\nif stable is True:\n    kind = 'stable'\n```\n\n### Alternative Solutions\n\nThe argument could be removed, though perhaps there are reasons for which it hasn't already been.\n\nOtherwise, I think it would be great if a warning message could be presented if anyone tries to use this argument (setting it to anything other than `None`). This way any confusion can be immediately resolved without someone having to think to check the documentation for what seems like a very straightforward argument.\n\n### Additional Context\n\nThere is also an `order` argument, which is similarly confusing, but probably a bit harder to change.",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64255/timeline',
  'performed_via_github_app': None,
  'state_reason': None,
  'pinned_comment': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64254',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64254/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64254/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64254/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64254',
  'id': 3969604459,
  'node_id': 'PR_kwDOAA0YD87FOI4w',
  'number': 64254,
  'title': 'DOC: Fix source link to use main branch (#64224)',
  'user': {'login': 'Asmi768',
   'id': 179839263,
   'node_id': 'U_kgDOCrghHw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/179839263?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Asmi768',
   'html_url': 'https://github.com/Asmi768',
   'followers_url': 'https://api.github.com/users/Asmi768/followers',
   'following_url': 'https://api.github.com/users/Asmi768/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Asmi768/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Asmi768/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Asmi768/subscriptions',
   'organizations_url': 'https://api.github.com/users/Asmi768/orgs',
   'repos_url': 'https://api.github.com/users/Asmi768/repos',
   'events_url': 'https://api.github.com/users/Asmi768/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Asmi768/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-02-20T17:30:57Z',
  'updated_at': '2026-02-20T17:30:57Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64254',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64254',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64254.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64254.patch',
   'merged_at': None},

In [98]:
len(df6)

30

In [99]:
for i in range(len(df6)):
    print(df6[i]['user']) # This code is iterating through the list of JSON objects in df6 and printing the value associated with the 'user' key for each object. The range(len(df6)) creates a sequence of indices from 0 to the length of df6 minus one, allowing you to access each element in the list using df6[i]. The ['user'] part retrieves the value of the 'user' key from each JSON object, which is then printed to the console.

{'login': 'tuhinsharma121', 'id': 6801780, 'node_id': 'MDQ6VXNlcjY4MDE3ODA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tuhinsharma121', 'html_url': 'https://github.com/tuhinsharma121', 'followers_url': 'https://api.github.com/users/tuhinsharma121/followers', 'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}', 'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions', 'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs', 'repos_url': 'https://api.github.com/users/tuhinsharma121/repos', 'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'tuhinsharma121', 'id': 6801780, 'node_id': 'MDQ6VXNlcjY4MDE3ODA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tuhinsharma121', 'html_url': 'https://github.com/tuhinsharma121', 'followers_url': 'https://api.github.com/users/tuhinsharma121/followers', 'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}', 'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions', 'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs', 'repos_url': 'https://api.github.com/users/tuhinsharma121/repos', 'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'tuhinsharma121', 'id': 6801780, 'node_id': 'MDQ6VXNlcjY4MDE3ODA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tuhinsharma121', 'html_url': 'https://github.com/tuhinsharma121', 'followers_url': 'https://api.github.com/users/tuhinsharma121/followers', 'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}', 'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions', 'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs', 'repos_url': 'https://api.github.com/users/tuhinsharma121/repos', 'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'yushiyangk', 'id': 9082950, 'node_id': 'MDQ6VXNlcjkwODI5NTA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/9082950?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yushiyangk', 'html_url': 'https://github.com/yushiyangk', 'followers_url': 'https://api.github.com/users/yushiyangk/followers', 'following_url': 'https://api.github.com/users/yushiyangk/following{/other_user}', 'gists_url': 'https://api.github.com/users/yushiyangk/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yushiyangk/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yushiyangk/subscriptions', 'organizations_url': 'https://api.github.com/users/yushiyangk/orgs', 'repos_url': 'https://api.github.com/users/yushiyangk/repos', 'events_url': 'https://api.github.com/users/yushiyangk/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yushiyangk/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'Asmi768', 'id': 179839263, 'node_id': 'U_kgDOCrghHw', 'avatar_url': 'https://avatars.githubusercontent.com/u/179839263?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Asmi768', 'html_url': 'https://github.com/Asmi768', 'followers_url': 'https://api.github.com/users/Asmi768/followers', 'following_url': 'https://api.github.com/users/Asmi768/following{/other_user}', 'gists_url': 'https://api.github.com/users/Asmi768/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Asmi768/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Asmi768/subscriptions', 'organizations_url': 'https://api.github.com/users/Asmi768/orgs', 'repos_url': 'https://api.github.com/users/Asmi768/repos', 'events_url': 'https://api.github.com/users/Asmi768/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Asmi768/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'olofahlen', 'id': 2066251, 'node_id': 'MDQ6VXNlcjIwNjYyNTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/2066251?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/olofahlen', 'html_url': 'https://github.com/olofahlen', 'followers_url': 'https://api.github.com/users/olofahlen/followers', 'following_url': 'https://api.github.com/users/olofahlen/following{/other_user}', 'gists_url': 'https://api.github.com/users/olofahlen/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/olofahlen/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/olofahlen/subscriptions', 'organizations_url': 'https://api.github.com/users/olofahlen/orgs', 'repos_url': 'https://api.github.com/users/olofahlen/repos', 'events_url': 'https://api.github.com/users/olofahlen/events{/privacy}', 'received_events_url': 'https://api.github.com/users/olofahlen/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'arnaudlegout', 'id': 7670869, 'node_id': 'MDQ6VXNlcjc2NzA4Njk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7670869?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/arnaudlegout', 'html_url': 'https://github.com/arnaudlegout', 'followers_url': 'https://api.github.com/users/arnaudlegout/followers', 'following_url': 'https://api.github.com/users/arnaudlegout/following{/other_user}', 'gists_url': 'https://api.github.com/users/arnaudlegout/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/arnaudlegout/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/arnaudlegout/subscriptions', 'organizations_url': 'https://api.github.com/users/arnaudlegout/orgs', 'repos_url': 'https://api.github.com/users/arnaudlegout/repos', 'events_url': 'https://api.github.com/users/arnaudlegout/events{/privacy}', 'received_events_url': 'https://api.github.com/users/arnaudlegout/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'hyoj0942', 'id': 50765163, 'node_id': 'MDQ6VXNlcjUwNzY1MTYz', 'avatar_url': 'https://avatars.githubusercontent.com/u/50765163?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/hyoj0942', 'html_url': 'https://github.com/hyoj0942', 'followers_url': 'https://api.github.com/users/hyoj0942/followers', 'following_url': 'https://api.github.com/users/hyoj0942/following{/other_user}', 'gists_url': 'https://api.github.com/users/hyoj0942/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/hyoj0942/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/hyoj0942/subscriptions', 'organizations_url': 'https://api.github.com/users/hyoj0942/orgs', 'repos_url': 'https://api.github.com/users/hyoj0942/repos', 'events_url': 'https://api.github.com/users/hyoj0942/events{/privacy}', 'received_events_url': 'https://api.github.com/users/hyoj0942/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'hyoj0942', 'id': 50765163, 'node_id': 'MDQ6VXNlcjUwNzY1MTYz', 'avatar_url': 'https://avatars.githubusercontent.com/u/50765163?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/hyoj0942', 'html_url': 'https://github.com/hyoj0942', 'followers_url': 'https://api.github.com/users/hyoj0942/followers', 'following_url': 'https://api.github.com/users/hyoj0942/following{/other_user}', 'gists_url': 'https://api.github.com/users/hyoj0942/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/hyoj0942/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/hyoj0942/subscriptions', 'organizations_url': 'https://api.github.com/users/hyoj0942/orgs', 'repos_url': 'https://api.github.com/users/hyoj0942/repos', 'events_url': 'https://api.github.com/users/hyoj0942/events{/privacy}', 'received_events_url': 'https://api.github.com/users/hyoj0942/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'arbolvlad', 'id': 101672391, 'node_id': 'U_kgDOBg9lxw', 'avatar_url': 'https://avatars.githubusercontent.com/u/101672391?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/arbolvlad', 'html_url': 'https://github.com/arbolvlad', 'followers_url': 'https://api.github.com/users/arbolvlad/followers', 'following_url': 'https://api.github.com/users/arbolvlad/following{/other_user}', 'gists_url': 'https://api.github.com/users/arbolvlad/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/arbolvlad/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/arbolvlad/subscriptions', 'organizations_url': 'https://api.github.com/users/arbolvlad/orgs', 'repos_url': 'https://api.github.com/users/arbolvlad/repos', 'events_url': 'https://api.github.com/users/arbolvlad/events{/privacy}', 'received_events_url': 'https://api.github.com/users/arbolvlad/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'arnaudlegout', 'id': 7670869, 'node_id': 'MDQ6VXNlcjc2NzA4Njk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7670869?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/arnaudlegout', 'html_url': 'https://github.com/arnaudlegout', 'followers_url': 'https://api.github.com/users/arnaudlegout/followers', 'following_url': 'https://api.github.com/users/arnaudlegout/following{/other_user}', 'gists_url': 'https://api.github.com/users/arnaudlegout/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/arnaudlegout/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/arnaudlegout/subscriptions', 'organizations_url': 'https://api.github.com/users/arnaudlegout/orgs', 'repos_url': 'https://api.github.com/users/arnaudlegout/repos', 'events_url': 'https://api.github.com/users/arnaudlegout/events{/privacy}', 'received_events_url': 'https://api.github.com/users/arnaudlegout/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'arnaudlegout', 'id': 7670869, 'node_id': 'MDQ6VXNlcjc2NzA4Njk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7670869?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/arnaudlegout', 'html_url': 'https://github.com/arnaudlegout', 'followers_url': 'https://api.github.com/users/arnaudlegout/followers', 'following_url': 'https://api.github.com/users/arnaudlegout/following{/other_user}', 'gists_url': 'https://api.github.com/users/arnaudlegout/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/arnaudlegout/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/arnaudlegout/subscriptions', 'organizations_url': 'https://api.github.com/users/arnaudlegout/orgs', 'repos_url': 'https://api.github.com/users/arnaudlegout/repos', 'events_url': 'https://api.github.com/users/arnaudlegout/events{/privacy}', 'received_events_url': 'https://api.github.com/users/arnaudlegout/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'd-s-dc', 'id': 68206552, 'node_id': 'MDQ6VXNlcjY4MjA2NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/68206552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/d-s-dc', 'html_url': 'https://github.com/d-s-dc', 'followers_url': 'https://api.github.com/users/d-s-dc/followers', 'following_url': 'https://api.github.com/users/d-s-dc/following{/other_user}', 'gists_url': 'https://api.github.com/users/d-s-dc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/d-s-dc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/d-s-dc/subscriptions', 'organizations_url': 'https://api.github.com/users/d-s-dc/orgs', 'repos_url': 'https://api.github.com/users/d-s-dc/repos', 'events_url': 'https://api.github.com/users/d-s-dc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/d-s-dc/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'kjmin622', 'id': 50573808, 'node_id': 'MDQ6VXNlcjUwNTczODA4', 'avatar_url': 'https://avatars.githubusercontent.com/u/50573808?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/kjmin622', 'html_url': 'https://github.com/kjmin622', 'followers_url': 'https://api.github.com/users/kjmin622/followers', 'following_url': 'https://api.github.com/users/kjmin622/following{/other_user}', 'gists_url': 'https://api.github.com/users/kjmin622/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/kjmin622/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/kjmin622/subscriptions', 'organizations_url': 'https://api.github.com/users/kjmin622/orgs', 'repos_url': 'https://api.github.com/users/kjmin622/repos', 'events_url': 'https://api.github.com/users/kjmin622/events{/privacy}', 'received_events_url': 'https://api.github.com/users/kjmin622/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'bittoby', 'id': 218712309, 'node_id': 'U_kgDODQlI9Q', 'avatar_url': 'https://avatars.githubusercontent.com/u/218712309?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bittoby', 'html_url': 'https://github.com/bittoby', 'followers_url': 'https://api.github.com/users/bittoby/followers', 'following_url': 'https://api.github.com/users/bittoby/following{/other_user}', 'gists_url': 'https://api.github.com/users/bittoby/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bittoby/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bittoby/subscriptions', 'organizations_url': 'https://api.github.com/users/bittoby/orgs', 'repos_url': 'https://api.github.com/users/bittoby/repos', 'events_url': 'https://api.github.com/users/bittoby/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bittoby/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'tuhinsharma121', 'id': 6801780, 'node_id': 'MDQ6VXNlcjY4MDE3ODA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tuhinsharma121', 'html_url': 'https://github.com/tuhinsharma121', 'followers_url': 'https://api.github.com/users/tuhinsharma121/followers', 'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}', 'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions', 'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs', 'repos_url': 'https://api.github.com/users/tuhinsharma121/repos', 'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}
{'login': 'tuhinsharma121', 'id': 6801780, 'node_id': 'MDQ6VXNlcjY4MDE3ODA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6801780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tuhinsharma121', 'html_url': 'https://github.com/tuhinsharma121', 'followers_url': 'https://api.github.com/users/tuhinsharma121/followers', 'following_url': 'https://api.github.com/users/tuhinsharma121/following{/other_user}', 'gists_url': 'https://api.github.com/users/tuhinsharma121/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tuhinsharma121/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tuhinsharma121/subscriptions', 'organizations_url': 'https://api.github.com/users/tuhinsharma121/orgs', 'repos_url': 'https://api.github.com/users/tuhinsharma121/repos', 'events_url': 'https://api.github.com/users/tuhinsharma121/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tuhinsharma121/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}